In [ ]:
!pip install numpy

In [1]:
import numpy as np

In [3]:
import time as tm

size_1 = 100000000

def pure_python_version():
    start_time_pp =  tm.time() ## time of start of code execution
    list1 = range(size_1)
    list2 = range(size_1)
    sum_list=[list1[i]+list2[i] for i in range(len(list1))]
    end_time_pp =  tm.time()
    return end_time_pp - start_time_pp ## end time for execution (difference)

def numpy_version():
    start_time_np = tm.time()
    array1 = np.arange(size_1)
    array2 =  np.arange(size_1)
    sum_array = array1 + array2
    end_time_np = tm.time()
    return end_time_np - start_time_np ## end time for execution (difference)

python_time = pure_python_version()
numpy_time  = numpy_version()

print("pure python version=",python_time)
print("numpy =",numpy_time)

pure python version= 16.946139574050903
numpy = 0.2737157344818115


In [7]:
my_list=[2,3,4,6,7,8]

In [8]:
aar = np.array(my_list)

In [10]:
type(aar)

numpy.ndarray

In [11]:
type(my_list)

list

In [13]:
aar.ndim

1

In [14]:
array_2 = [[1,2,3],[4,5,6],[7,8,9]]
array_3= np.array(array_2)
array_3
type(array_3)

numpy.ndarray

In [15]:
array_3.ndim

2

In [16]:
array_3.shape

(3, 3)

In [17]:
array_3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [18]:
array_3.size

9

In [21]:
a = np.array([1, 2, 3,7,5,1], ndmin = 3) 
print (a)
np.ndim(a)

[[[1 2 3 7 5 1]]]


3

In [22]:
a = np.array([1, 2, 3, 4], dtype = complex) 
print (a)

[1.+0.j 2.+0.j 3.+0.j 4.+0.j]


In [23]:
len(array_3)

3

In [24]:
array_3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [25]:
array_3[2]

array([7, 8, 9])

In [26]:
array_3[:,1]

array([2, 5, 8])

In [30]:
array_3[:1,1:]

array([[2, 3]])

In [31]:
array_3[2:,:2]

array([[7, 8]])

In [32]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [33]:
np.arange(100,10, -10)

array([100,  90,  80,  70,  60,  50,  40,  30,  20])

In [34]:
np.zeros(3,dtype=int)

array([0, 0, 0])

In [35]:
np.zeros((3,2),dtype=int)

array([[0, 0],
       [0, 0],
       [0, 0]])

In [36]:
np.ones((2,3),dtype=int)

array([[1, 1, 1],
       [1, 1, 1]])

In [37]:
np.eye(3,3) 

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [41]:
np.linspace(1, 10, 20)

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

In [42]:
np.linspace(-20,-15,10)

array([-20.        , -19.44444444, -18.88888889, -18.33333333,
       -17.77777778, -17.22222222, -16.66666667, -16.11111111,
       -15.55555556, -15.        ])

In [43]:
array_3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [44]:
array_3.reshape(1,9)

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [45]:
array_3.reshape(9,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [46]:
x=[[1,2,3,4],[4,5,6,7],[7,8,9,10],[10,11,12,13]]
x=np.array(x)
x

array([[ 1,  2,  3,  4],
       [ 4,  5,  6,  7],
       [ 7,  8,  9, 10],
       [10, 11, 12, 13]])

In [49]:
x.reshape(2,8)

array([[ 1,  2,  3,  4,  4,  5,  6,  7],
       [ 7,  8,  9, 10, 10, 11, 12, 13]])

In [50]:
x

array([[ 1,  2,  3,  4],
       [ 4,  5,  6,  7],
       [ 7,  8,  9, 10],
       [10, 11, 12, 13]])

In [51]:
x.min()

1

In [52]:
x.max()

13

In [53]:
x.mean()

7.0

In [54]:
x.var()

12.5

In [55]:
x.std()

3.5355339059327378

In [56]:
x.sum()

112

In [57]:
x

array([[ 1,  2,  3,  4],
       [ 4,  5,  6,  7],
       [ 7,  8,  9, 10],
       [10, 11, 12, 13]])

In [58]:
x.min(axis=0)

array([1, 2, 3, 4])

In [59]:
x.max(axis=0)

array([10, 11, 12, 13])

In [60]:
x.min(axis=1)

array([ 1,  4,  7, 10])

In [61]:
x.max(axis=1)

array([ 4,  7, 10, 13])

In [62]:
x.mean(axis=0)

array([5.5, 6.5, 7.5, 8.5])

In [63]:
x.sum(axis=0)

array([22, 26, 30, 34])

In [64]:
x

array([[ 1,  2,  3,  4],
       [ 4,  5,  6,  7],
       [ 7,  8,  9, 10],
       [10, 11, 12, 13]])

In [65]:
x.argmin()

0

In [67]:
x.argmax()

15

In [68]:
X = x.flatten()

In [69]:
X

array([ 1,  2,  3,  4,  4,  5,  6,  7,  7,  8,  9, 10, 10, 11, 12, 13])

In [70]:
x.transpose()

array([[ 1,  4,  7, 10],
       [ 2,  5,  8, 11],
       [ 3,  6,  9, 12],
       [ 4,  7, 10, 13]])

In [71]:
A = np.array([ [4, 10, 11], [21, 22, 23], [31, 32, 33] ])
B = np.ones((3,3))
print(A)

[[ 4 10 11]
 [21 22 23]
 [31 32 33]]


In [72]:
A

array([[ 4, 10, 11],
       [21, 22, 23],
       [31, 32, 33]])

In [73]:
B

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [74]:
A+B

array([[ 5., 11., 12.],
       [22., 23., 24.],
       [32., 33., 34.]])

In [75]:
A*B

array([[ 4., 10., 11.],
       [21., 22., 23.],
       [31., 32., 33.]])

In [76]:
A/B

array([[ 4., 10., 11.],
       [21., 22., 23.],
       [31., 32., 33.]])

In [77]:
B/A

array([[0.25      , 0.1       , 0.09090909],
       [0.04761905, 0.04545455, 0.04347826],
       [0.03225806, 0.03125   , 0.03030303]])

In [78]:
A**2

array([[  16,  100,  121],
       [ 441,  484,  529],
       [ 961, 1024, 1089]])

In [79]:
A-B

array([[ 3.,  9., 10.],
       [20., 21., 22.],
       [30., 31., 32.]])

In [80]:
A%3

array([[1, 1, 2],
       [0, 1, 2],
       [1, 2, 0]], dtype=int32)

In [81]:
A.dtype

dtype('int32')

In [82]:
A//3

array([[ 1,  3,  3],
       [ 7,  7,  7],
       [10, 10, 11]], dtype=int32)

In [84]:
A

array([[ 4, 10, 11],
       [21, 22, 23],
       [31, 32, 33]])

In [85]:
B

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [83]:
np.dot(A,B)

array([[25., 25., 25.],
       [66., 66., 66.],
       [96., 96., 96.]])

In [86]:
np.sqrt(A)

array([[2.        , 3.16227766, 3.31662479],
       [4.58257569, 4.69041576, 4.79583152],
       [5.56776436, 5.65685425, 5.74456265]])

In [87]:
np.exp(A)

array([[5.45981500e+01, 2.20264658e+04, 5.98741417e+04],
       [1.31881573e+09, 3.58491285e+09, 9.74480345e+09],
       [2.90488497e+13, 7.89629602e+13, 2.14643580e+14]])

In [88]:
np.log(A)

array([[1.38629436, 2.30258509, 2.39789527],
       [3.04452244, 3.09104245, 3.13549422],
       [3.4339872 , 3.4657359 , 3.49650756]])

In [89]:
a=np.array([[11.667,23.662],[33.21,45.887]])

In [90]:
a

array([[11.667, 23.662],
       [33.21 , 45.887]])

In [94]:
np.around(a)

array([[12., 24.],
       [33., 46.]])

In [95]:
A

array([[ 4, 10, 11],
       [21, 22, 23],
       [31, 32, 33]])

In [96]:
B

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [97]:
np.concatenate([A,B])

array([[ 4., 10., 11.],
       [21., 22., 23.],
       [31., 32., 33.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [100]:
np.random.randint(2,10,(3,3))

array([[2, 8, 5],
       [8, 4, 2],
       [5, 4, 4]])

In [102]:
np.random.rand(3,3)

array([[0.06746574, 0.77441819, 0.54998231],
       [0.96625763, 0.64329375, 0.87768103],
       [0.79358024, 0.78474648, 0.53410957]])

In [103]:
np.nan

nan

In [107]:
np.random.randn(4,3)

array([[-0.10487598,  0.47343055, -0.03015891],
       [-1.49846436,  0.14213868,  0.87339878],
       [ 0.83986474, -0.05854432, -1.36168872],
       [-1.11893565,  1.15869362, -0.0437114 ]])